// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkbfjteqdnfgycjxavqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrYmZqdGVxZG5mZ3ljanhhdnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyMzMzMTcsImV4cCI6MjA3ODgwOTMxN30.LpA59vLOQ2nCGvch6rDi4RnOjLuNDoNjs339vNwrxpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});